//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.09 at 05:29:57 PM PKT 
//


package org.w3._2001.xmlschema;

import java.time.LocalDate;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2 extends XmlAdapter<String, LocalDate> {


    public LocalDate unmarshal(String value) {
        return (com.softech.ls360.storefront.proxy.webservice.binder.XSDateCustomBinder.parseDateTime(value));
    }

    public String marshal(LocalDate value) {
        return (com.softech.ls360.storefront.proxy.webservice.binder.XSDateCustomBinder.printDateTime(value));
    }

}
