//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.02 at 08:06:13 PM PKT 
//


package com.softech.ls360.storefront.proxy.webservice.messages.orderdetails;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.ls360.storefront.proxy.webservice.messages.orderdetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderServiceResponse_QNAME = new QName("http://www.example.org/OrderService", "OrderServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.ls360.storefront.proxy.webservice.messages.orderdetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderServiceRequest }
     * 
     */
    public OrderServiceRequest createOrderServiceRequest() {
        return new OrderServiceRequest();
    }

    /**
     * Create an instance of {@link OrderServiceRequestType }
     * 
     */
    public OrderServiceRequestType createOrderServiceRequestType() {
        return new OrderServiceRequestType();
    }

    /**
     * Create an instance of {@link OrderServiceResponseType }
     * 
     */
    public OrderServiceResponseType createOrderServiceResponseType() {
        return new OrderServiceResponseType();
    }

    /**
     * Create an instance of {@link OrderItemsList }
     * 
     */
    public OrderItemsList createOrderItemsList() {
        return new OrderItemsList();
    }

    /**
     * Create an instance of {@link OrderItem }
     * 
     */
    public OrderItem createOrderItem() {
        return new OrderItem();
    }

    /**
     * Create an instance of {@link OrderList }
     * 
     */
    public OrderList createOrderList() {
        return new OrderList();
    }

    /**
     * Create an instance of {@link RefundDetail }
     * 
     */
    public RefundDetail createRefundDetail() {
        return new RefundDetail();
    }

    /**
     * Create an instance of {@link OrderDetailResponse }
     * 
     */
    public OrderDetailResponse createOrderDetailResponse() {
        return new OrderDetailResponse();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link OrderAdjustment }
     * 
     */
    public OrderAdjustment createOrderAdjustment() {
        return new OrderAdjustment();
    }

    /**
     * Create an instance of {@link OrdersList }
     * 
     */
    public OrdersList createOrdersList() {
        return new OrdersList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/OrderService", name = "OrderServiceResponse")
    public JAXBElement<OrderServiceResponseType> createOrderServiceResponse(OrderServiceResponseType value) {
        return new JAXBElement<OrderServiceResponseType>(_OrderServiceResponse_QNAME, OrderServiceResponseType.class, null, value);
    }

}
